import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nethra
 */
public class Dbms extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Dbms
     */
    public Dbms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable111 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        queryTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Query 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTable111.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(jTable111);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1300, 190));

        jButton2.setText("Query 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jButton3.setText("Query 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton4.setText("Query 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jButton5.setText("Query 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton6.setText("Query 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton7.setText(" Query 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jButton8.setText("Query 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jButton9.setText("Query 9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButton10.setText("Query 10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        queryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryTxtActionPerformed(evt);
            }
        });
        getContentPane().add(queryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 820, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nethra\\Desktop\\imgs\\13988.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 732));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//rivate void Filecombo()
        

    
    
    
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
      try{
        con=Connect.ConnectDB();
        queryTxt.setText("DISPLAY PATIENT DETAILS WHO GOT FEVER");
       String sql="SELECT DISTINCT p.PatientName,ap.* FROM patientregistration p,admitpatient_room ap WHERE Disease='Fever' and p.PatientID=ap.PatientID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT p.PatientName,d.DoctorName FROM admitpatient_room ar,patientregistration p,doctor d WHERE p.PatientID=ar.PatientID and d.DoctorID=ar.DoctorID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT ServiceCharges,PatientName from patientregistration NATURAL join services";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT pr.PatientName,r.RoomType,r.RoomCharges FROM patientregistration pr,admitpatient_room ar,room r WHERE pr.PatientID=ar.PatientID and r.RoomNo=ar.RoomNo";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="select DISTINCT r.RoomNo,d.DoctorName from doctor d,admitpatient_room ar,room r where ar.RoomNo=r.RoomNo and d.DoctorID=ar.DoctorID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT * FROM `doctor` WHERE DateOfJoining>2017";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="select DISTINCT p.*,d.* from doctor d,patientregistration p,admitpatient_room ar where ar.PatientID=p.PatientID and d.DoctorID=ar.DoctorID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT DISTINCT p.PatientName,ap.* FROM patientregistration p,admitpatient_room ap WHERE Disease='Fever' and p.PatientID=ap.PatientID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT DISTINCT p.PatientName,ap.* FROM patientregistration p,admitpatient_room ap WHERE Disease='Fever' and p.PatientID=ap.PatientID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 try{
        con=Connect.ConnectDB();
       String sql="SELECT DISTINCT p.PatientName,ap.* FROM patientregistration p,admitpatient_room ap WHERE Disease='Fever' and p.PatientID=ap.PatientID";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         jTable111.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void queryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queryTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dbms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dbms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dbms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dbms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dbms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable111;
    private javax.swing.JTextField queryTxt;
    // End of variables declaration//GEN-END:variables
}
